Add blog post about PayPal updates and financing options
solidusio/solidus-site pull request #418
Opened 2020-11-09 21:47 UTC by seand7565

2020-11-11 11:33 UTC, mtylty requested changes

2020-11-11 11:33 UTC, mtylty commented on source/blog/2020-11-10-add-credit-messaging-to-your-solidus-app.html.markdown
> +The installation of this extension is pretty simple, and you can read the details in the [extension README.](https://github.com/solidusio/solidus_paypal_braintree#installation) Once installed, you'll
full stop should go outside the link

2020-11-11 11:33 UTC, mtylty commented on source/blog/2020-11-10-add-credit-messaging-to-your-solidus-app.html.markdown
> +Good news for this extension - installation is simple, and PayPal messaging is enabled by default. From Solidus 2.11, you can install this extension during the initial Solidus installation. You can r
fullstop outside the link, like above

2020-11-23 08:33 UTC, kennyadsl approved these changes

2020-11-23 08:33 UTC, merged